nucleya = 'Fuck That Shit!!!'

print(nucleya.capitalize())
print(nucleya.swapcase())
print(len(nucleya))
print(nucleya.replace('Fuck', 'Coitus'))
print(nucleya.count('h'))
print(nucleya.startswith('Fuck'))
print(nucleya.endswith('zz'))
print(nucleya.split())
print(nucleya.find('z'))
print(nucleya.index('!'))
print(nucleya.isalnum())
print(nucleya.isalpha())
print(nucleya.isnumeric())